version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: discord_postgres
    restart: always
    environment:
      POSTGRES_USER: aritz
      POSTGRES_PASSWORD: aritz
      POSTGRES_DB: discord_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: discord_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://aritz:aritz@postgres-db:5432/discord_db?schema=public
      SECRET: SECRET
    depends_on:
      - postgres-db

volumes:
  postgres_data:
